name: publish

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Container Registry
      uses: docker/login-action@v1
      with:
        username: jeremyk6
        password: ${{ secrets.PKG_SECRET }}

    - name: Build the Docker image
      run: |
        docker build . --tag jeremyk6/le-carrefour-nelson:latest
        docker push jeremyk6/le-carrefour-nelson:latest
